org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Environment Properties
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.235
loader_version_range=[1,)

# Refined Storage 2 (compiled against the full mod jar from https://maven.creeperhost.net)
# https://github.com/refinedmods/refinedstorage2
refinedstorage_version=2.0.9

## Mod Properties
mod_id=nexrstweaks
mod_name=NexRSTweaks
mod_license=MIT
mod_version=0.1.0
mod_group_id=com.nexy451z.nexrstweaks
